### ISSUE TITLE
Mental map

### ISSUE THREAD

**Issue by LuisAlexisMorales** [SistemasTecTlaxiaco/actividad-4-mapa-mental-LuisAlexisMorales#2]
![conjuntos relaciones y funcuines (1)-1](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-LuisAlexisMorales/assets/143825449/da4457ca-181d-483d-acd3-d577aa048cef)

**Comment by Maritza2893** [comment]
Manejo conceptual y dominio del tema: 17%
Relación entre los conceptos incluidos en el mapa: 22% 
Calidad de la presentación: 15%
Jerarquía: 20%
promedio final: 14.8%
Evaluado por Maritza

**Comment by josealfredo79** [comment]
Revisado..
